### PR TITLE
Concept Review

### PR DESCRIPTION
**Pull request by SamPassmore**
Hi Simon,

I have gone through the concepts file & I don't think there are any that have the same meaning but different IDs across the two DBs. 

I created two issues relating to problems I noticed, but I think both of them are pretty straightforward if I understand how things work correctly. Let me know if you need more detail on those. 

In the creation of the concept file it looks like when ever there was a repeat of relatives in the ID (e.g. FF), the automatically made description didn't parse this right. It would have Father (instead of Father's father). I have manually fixed this for the most part - as I was having a close look at the concepts anyway. So hopefully that is fixed now. 

I used my text editor to format the file into columns to make it easier to edit, but this has annoyingly meant it is not obvious where my changes were from the original file.

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
thanks Sam!

**Comment by SimonGreenhill** [comment]
Hmm, looks like we still need these ones, any suggestions?

WARNING /Users/simon/projects/kinship/data/kinbank/cldf/forms.csv:111077 Key WifesSameGroup not found in table parameters.csv
WARNING /Users/simon/projects/kinship/data/kinbank/cldf/forms.csv:111078 Key HusbandsSameGroup not found in table parameters.csv
WARNING /Users/simon/projects/kinship/data/kinbank/cldf/forms.csv:177897 Key mWMBD not found in table parameters.csv
WARNING /Users/simon/projects/kinship/data/kinbank/cldf/forms.csv:177898 Key mWMBS not found in table parameters.csv
WARNING /Users/simon/projects/kinship/data/kinbank/cldf/forms.csv:177899 Key mWMZD not found in table parameters.csv
WARNING /Users/simon/projects/kinship/data/kinbank/cldf/forms.csv:177900 Key mWMZS not found in table parameters.csv
WARNING /Users/simon/projects/kinship/data/kinbank/cldf/forms.csv:178118 Key mJan not found in table parameters.csv
WARNING /Users/simon/projects/kinship/data/kinbank/cldf/forms.csv:178209 Key fJan not found in table parameters.csv

**Comment by SamPassmore** [comment]
I didn't delete any rows from the concepts file, so unsure why these
warnings appeared.
How do the parameters file and concepts file interact? From issue #3: it
takes the concepts file, and removes any parameters with zero counts. Does
it also add new parameters? If not, will this be caused by parameters not
seen before?

The first two are my fault, they come from komb1273 in the parabank set - I
was editing the descriptions and standardized all husband/wife to lower
case, but didn't realise this was being used as a key in PB. I have fixed
this.
middle four come from nort1551 in varikin. This is also the file that WZZD
was in and has been removed. I went through the original source to figure
out why they had appeared, and I think I added some more kinterms that I
spotted in the source and weren't picked up - this was only updated in the
varikin repo 2 days ago.
The last two are obviously the google sheets error that is haunting me,
within opat1246, which I have now changed. It looks like I changed a copy
of a file previously.

**Comment by SimonGreenhill** [comment]
Ahah, ok I've sorted most of these, still stuck with the middle four which all appear to be in the `lexibank_format/raw/North_Northern_Paiute_nort1551.txt` file. Any chance you can update this?

And the concepts file is the parameters list, it's specified by hand in ./etc/concepts.csv. This file is intended to contain the parameters in the database a priori and the lexibank code loads this and injects it into the cldf/parameters.csv (but leaving out any concepts/parameters that do not appear in the data (i.e. whatever goes into lexemes.csv). 

So, ./etc/concepts.csv only changes if we change it. ./cldf/parameters.csv is generated from ./etc/concepts.csv, with filtering.

**Comment by SimonGreenhill** [comment]
Also, I guess it's silly for the merging/import code to use your 'lexibank_format' dir, because that just adds another step for you.

**Comment by SamPassmore** [comment]
I added some rows to concepts with the new concepts I had added. 
Sorry I didn't realise that we needed to add new concepts by hand. 

merging from the lexibank_format folder is probably best. I have a build script that goes from googledrive to that format already, so there is not much effort for me. There is some pre-processing that happens in that script too. 

I guess the best-practice way of building kinbank would be via this script - but it takes like 3 hours to run because of the limits on the google API. So it would be best for us to shut down google drive. I will try to do that soon - but need to talk to some people who might still be using it.

**Comment by SimonGreenhill** [comment]
Great, thanks Sam. I'll leave the code reading from `lexibank_format` for now.

**Pull request merged**
