### PR TITLE
Created mand1415 and kore1280

### PR DESCRIPTION
**Pull request by imogen-mcara**
Created workbooks Mandarin_China_mand1415 and Korean_kore1280 and filled them in to the best of my ability. Added medadata to languages and sources to Zotero and sources.bib. Within hours contracted I could not find some sources for words I know to be in use; in these cases "word" and "comment" are filled and "source" has been left blank.

### CODE REVIEW

**Comment by SamPassmore** [comment]
Hi Imogen, 

Thanks for providing this data, although unfortunately this repository isn't for adding data - it should be added to the dataset that you are working on (i.e.  who you are working with), as it says on the homepage here:
https://github.com/kinbank/kinbank

Let me know who you are working with and I can point you to the right repository. 

Sam

**Comment by imogen-mcara** [comment]
Hi Sam,

Sorry about that. I am working with Fiona on the Varikin project.

Best wishes,
Imogen
________________________________

**Comment by SamPassmore** [comment]
Ok. Then you want to make changes to the kinbank/varikin repository (everything is set up the same). 

https://github.com/kinbank/varikin

If you make the same changes you have made here in that repository then I can merge the pull request. The changes made here would be lost everytime we update unfortunately!

**Comment by fionajordan** [comment]
Oops - I think we need to update the instruction manual as well! I'll do that. 
Fiona

**Pull request closed without merging**
